[
  ./../services/openssh.nix
  ./wirelessregdom.nix
  ./../substituters
  ./nix.nix
  ./audit.nix
  ./observability.nix
  ./../services/ivpn.nix
  ./../services/syncthing.nix
  ./devops.nix
  ./utilities.nix
  ./acme.nix
]
