[common]
system = "x86_64-linux"
timezone = "America/New_York" # Los_Angeles

[laptop]
hostname = "grindenstern"
user-fullname = "Quinn Dougherty"
# one of xmonad, xfce, gnome, kde, exwm
desktop = "kde"

[phone]
hostname = "risencrantz"
user-fullname = "Quinn Dougherty"
system = "aarch64-linux"

[server]
hostname = "a-guy-for-a-thing"
user-fullname = "Server Admin"
ip = "192.168.6.33"
static4 = "192.168.42.42"

[uptime]
hostname = "the-band-back-together"
user-fullname = "Monitor Admin"
ip = "143.198.58.137"

[ubuntu]
hostname = "cogrindenstern"
user-fullname = "Quinn Dougherty"
