[common]
system = "x86_64-linux"
timezone = "America/Los_Angeles"

[laptop]
hostname = "rise"
user-fullname = "Quinn Dougherty"
# one of xmonad, xfce, gnome, kde, exwm
desktop = "kde"

[phone]
hostname = "corise"
user-fullname = "Quinn Dougherty"
system = "aarch64-linux"

[server]
hostname = "grind"
user-fullname = "Server Admin"
ip = "135.180.4.12"

[uptime]
hostname = "cogrind"
user-fullname = "Monitor Admin"
ip = "143.198.58.137"

[ubuntu]
hostname = "cogrindenstern"
user-fullname = "Quinn Dougherty"
