[common]
system = "x86_64-linux"
timezone = "America/Los_Angeles"

[laptop]
hostname = "laptop"
username = "qd"
user-fullname = "Quinn Dougherty"

[phone]
hostname = "phone"
username = "qd"
user-fullname = "Quinn Dougherty"
system = "aarch64-linux"

[server]
hostname = "server"
username = "admin"
user-fullname = "Hercules Administrator Latitude"
ip = "192.168.6.18"

[chat]
hostname = "chat"
username = "synapse-admin"
user-fullname = "Matrix Administrator"
ip = ""
