[common]
system = "x86_64-linux"
timezone = "America/New_York"

[framework]
hostname = "fw"
username = "qd"
user-fullname = "Quinn Dougherty"

[pinephone]
hostname = "pinephone"
username = "qd"
user-fullname = "Quinn Dougherty"
system = "aarch64-linux"

[agent-digitalocean]
hostname = "herc-agent-digitalocean"
username = "herc-admin"
user-fullname = "Hercules Administrator Digital Ocean"
volume = "volume-nyc3-01"
ip = "142.93.190.80"

[agent-latitude]
hostname = "herc-agent-latitude"
username = "herc-admin"
user-fullname = "Hercules Administrator Latitude"
ip = "192.168.0.90"

[chat]
hostname = "matrix-server"
username = "synapse-admin"
user-fullname = "Matrix Administrator"
ip = ""
