# Autogenerated by Mobile Nixos installer
{ config, lib, pkgs, ... }:

{
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/11d61975-61dd-4032-8b18-fd6769eefcba";
    fsType = "ext4";
  };
  nix.settings.max-jobs = lib.mkDefault 2;
}
